services:
  mysql:
    container_name: mysql
    image: marlonzl7/conexao-academica:mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
    - mysql_data:/var/lib/mysql
    - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"

  site:
    container_name: web-data-viz
    image: marlonzl7/conexao-academica:web-data-viz
    restart: always
    environment:
    volumes:
    - 
    - 
    ports:
      - "${APP_PORT}:80"


  etl-java:
    container_name: etl-java
    image: marlonzl7/conexao-academica:etl-java
    environment:
    volumes:
    - 
    ports:
      - ":"

volumes:
  mysql_data:
  site_data:
  etl_data:
